package com.civiguard.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "geofence_polygon_points")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class GeoFencePoint {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "geofence_id")
    private GeoFence geofence;

    @Embedded
    private Location location;

    @Column(name = "point_order", nullable = false)
    private Integer pointOrder;

    // Getters and setters are generated by @Data from Lombok
}
